version: '3'
services:
  gai-typesense:
    image: typesense/typesense:26.0
    container_name: gai-typesense
    restart: always
    env_file: .env
    ports:
      - '8108:8108'
    volumes:
      - ./gaidata:/typesensedata
    command: '--data-dir /typesensedata --api-key=xyz --enable-cors'
