packages:
  - 'apps/georgeai-web'
  - 'apps/georgeai-webapp'
  - 'apps/georgeai-backend'
  - 'services/smb-crawler-service'
  - 'services/model-manager-service'
  - 'services/ai-service-worker'
  - 'packages/*'
  - '!packages/ai-models'
