name: Documentation Improvement
description: Suggest improvements to documentation
title: '[Docs]: '
labels: ['documentation']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs improvement?
      options:
        - User Documentation
        - Developer Documentation
        - Self-Hosting Guide
        - API Documentation
        - Code Comments
        - README
        - Other
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: What's Wrong or Missing?
      description: Describe the issue with the current documentation
      placeholder: The documentation is unclear about...
    validations:
      required: true

  - type: textarea
    id: improvement
    attributes:
      label: Suggested Improvement
      description: What should be added, changed, or clarified?
      placeholder: It would be clearer if...
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Link or path to the documentation that needs improvement
      placeholder: e.g., docs/self-hosting.md, https://george-ai.net/docs
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or examples
      placeholder: Any additional information
    validations:
      required: false

  - type: checkboxes
    id: contribute
    attributes:
      label: Contribution
      options:
        - label: I am willing to submit a PR to fix this documentation issue
          required: false
