name: Feature Request
description: Suggest a new feature or enhancement
title: '[Feature]: '
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: A clear description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe alternatives you've considered
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of George AI does this feature relate to?
      options:
        - Frontend/UI
        - Backend/API
        - Database/Storage
        - AI/LLM Integration
        - Search/Embeddings
        - Authentication
        - Crawlers/Data Collection
        - Enrichments
        - Documentation
        - DevOps/Deployment
        - Other
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority (from your perspective)
      description: How important is this feature to you?
      options:
        - Critical - Cannot use without it
        - High - Would significantly improve my workflow
        - Medium - Nice to have
        - Low - Optional enhancement
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Any additional information
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to make sure this feature hasn't been requested
          required: true
        - label: I am willing to contribute to implementing this feature (optional but appreciated)
          required: false
