export const WORKSPACES_FOLDER_NAME = 'workspaces'
export const LIBRARIES_FOLDER_NAME = 'libraries'
export const DOCUMENTS_FOLDER_NAME = 'documents'
export const EXTRACTIONS_FOLDER_NAME = 'extractions'
export const FRAGMENTS_FOLDER_NAME = 'fragments'
export const SOURCE_FILE_NAME = 'source_file'
export const ATTACHMENTS_FOLDER_NAME = 'attachments'

export const ATTACHMENTS_BACKUP_FOLDER_NAME = 'attachments_backup'
export const EXTRACTIONS_BACKUP_FOLDER_NAME = 'extractions_backup'
export const DOCUMENTS_BACKUP_FOLDER_NAME = 'documents_backup'
export const LIBRARIES_BACKUP_FOLDER_NAME = 'libraries_backup'
export const WORKSPACES_BACKUP_FOLDER_NAME = 'workspaces_backup'

export const MANIFEST_FILE_NAME = 'manifest.json'
