export const WORKER_TYPES = [
  'WORKER_MANAGER',
  'WORKSPACE_MANAGER',
  'DOCUMENT_PROCESSING',
  'MODEL_CALL_RESPONDER',
  'PROVIDER_INSTANCE_MANAGER',
  'PROVIDER_INSTANCE_RESPONDER',
] as const
export type WorkerType = (typeof WORKER_TYPES)[number]
