export const queryKeys = {
  KeycloakInstance: 'KeycloakInstance',
  AiAssistants: 'AiAssistants',
  AiAssistantForEdit: 'AiAssistantForEdit',
  MyAiAssistants: 'MyAiAssistants',
  AiAssistantLibraries: 'AiAssistantLibraries',
  AiLibrary: 'AiLibrary',
  AiLibraries: 'AiLibraries',
  AiLibraryFiles: 'AiLibraryFiles',
  GoogleDriveFiles: 'GoogleDriveFiles',
  Conversations: 'Conversations',
  Conversation: 'Conversation',
  ConversationMessages: 'ConversationMessages',
  ConversationUsers: 'ConversationUsers',
  ConversationAssignableUsers: 'ConversationAssignableUsers',
  ConversationAssignableAssistants: 'ConversationAssignableAssistants',
  ConversationInvitation: 'ConversationInvitation',
  BackendUrl: 'BackendUrl',
  UserProfileForEdit: 'UserProfileForEdit',
}
