export const queryKeys = {
  AiAssistants: 'AiAssistants',
  AiLibrary: 'AiLibrary',
  AiLibraries: 'AiLibraries',
  AiLibraryFiles: 'AiLibraryFiles',
  GoogleDriveFiles: 'GoogleDriveFiles',
  Conversations: 'Conversations',
  Conversation: 'Conversation',
  Language: 'Language',
  Theme: 'Theme',
  User: 'User',
  Users: 'Users',
  ConversationInvitation: 'ConversationInvitation',
  BackendUrl: 'BackendUrl',
  UserProfileForEdit: 'UserProfileForEdit',
}
