export const queryKeys = {
  KeycloakInstance: 'KeycloakInstance',
  AiAssistant: 'AiAssistant',
  AiAssistants: 'AiAssistants',
  MyAiAssistants: 'MyAiAssistants',
  AiAssistantLibraries: 'AiAssistantLibraries',
  AiLibraries: 'AiLibraries',
  AiLibraryFiles: 'AiLibraryFiles',
  GoogleDriveFiles: 'GoogleDriveFiles',
  Conversations: 'Conversations',
  Conversation: 'Conversation',
  ConversationMessages: 'ConversationMessages',
  Users: 'Users',
  ConversationAssignableAssistants: 'ConversationAssignableAssistants',
  ConversationInvitation: 'ConversationInvitation',
  BackendUrl: 'BackendUrl',
  UserProfileForEdit: 'UserProfileForEdit',
}
