/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProfileImport } from './routes/profile'
import { Route as LangchainChatImport } from './routes/langchain-chat'
import { Route as ContactImport } from './routes/contact'
import { Route as IndexImport } from './routes/index'
import { Route as KnowledgeIndexImport } from './routes/knowledge/index'
import { Route as AssistantsIndexImport } from './routes/assistants/index'
import { Route as KnowledgeNewImport } from './routes/knowledge/new'
import { Route as KnowledgeAuthGoogleImport } from './routes/knowledge/auth-google'
import { Route as KnowledgeKnowledgeSourceIdImport } from './routes/knowledge/$knowledgeSourceId'
import { Route as AssistantsNewImport } from './routes/assistants/new'
import { Route as AssistantsAssistantIdImport } from './routes/assistants/$assistantId'

// Create/Update Routes

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const LangchainChatRoute = LangchainChatImport.update({
  id: '/langchain-chat',
  path: '/langchain-chat',
  getParentRoute: () => rootRoute,
} as any)

const ContactRoute = ContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const KnowledgeIndexRoute = KnowledgeIndexImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => rootRoute,
} as any)

const AssistantsIndexRoute = AssistantsIndexImport.update({
  id: '/assistants/',
  path: '/assistants/',
  getParentRoute: () => rootRoute,
} as any)

const KnowledgeNewRoute = KnowledgeNewImport.update({
  id: '/knowledge/new',
  path: '/knowledge/new',
  getParentRoute: () => rootRoute,
} as any)

const KnowledgeAuthGoogleRoute = KnowledgeAuthGoogleImport.update({
  id: '/knowledge/auth-google',
  path: '/knowledge/auth-google',
  getParentRoute: () => rootRoute,
} as any)

const KnowledgeKnowledgeSourceIdRoute = KnowledgeKnowledgeSourceIdImport.update(
  {
    id: '/knowledge/$knowledgeSourceId',
    path: '/knowledge/$knowledgeSourceId',
    getParentRoute: () => rootRoute,
  } as any,
)

const AssistantsNewRoute = AssistantsNewImport.update({
  id: '/assistants/new',
  path: '/assistants/new',
  getParentRoute: () => rootRoute,
} as any)

const AssistantsAssistantIdRoute = AssistantsAssistantIdImport.update({
  id: '/assistants/$assistantId',
  path: '/assistants/$assistantId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/langchain-chat': {
      id: '/langchain-chat'
      path: '/langchain-chat'
      fullPath: '/langchain-chat'
      preLoaderRoute: typeof LangchainChatImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/assistants/$assistantId': {
      id: '/assistants/$assistantId'
      path: '/assistants/$assistantId'
      fullPath: '/assistants/$assistantId'
      preLoaderRoute: typeof AssistantsAssistantIdImport
      parentRoute: typeof rootRoute
    }
    '/assistants/new': {
      id: '/assistants/new'
      path: '/assistants/new'
      fullPath: '/assistants/new'
      preLoaderRoute: typeof AssistantsNewImport
      parentRoute: typeof rootRoute
    }
    '/knowledge/$knowledgeSourceId': {
      id: '/knowledge/$knowledgeSourceId'
      path: '/knowledge/$knowledgeSourceId'
      fullPath: '/knowledge/$knowledgeSourceId'
      preLoaderRoute: typeof KnowledgeKnowledgeSourceIdImport
      parentRoute: typeof rootRoute
    }
    '/knowledge/auth-google': {
      id: '/knowledge/auth-google'
      path: '/knowledge/auth-google'
      fullPath: '/knowledge/auth-google'
      preLoaderRoute: typeof KnowledgeAuthGoogleImport
      parentRoute: typeof rootRoute
    }
    '/knowledge/new': {
      id: '/knowledge/new'
      path: '/knowledge/new'
      fullPath: '/knowledge/new'
      preLoaderRoute: typeof KnowledgeNewImport
      parentRoute: typeof rootRoute
    }
    '/assistants/': {
      id: '/assistants/'
      path: '/assistants'
      fullPath: '/assistants'
      preLoaderRoute: typeof AssistantsIndexImport
      parentRoute: typeof rootRoute
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/langchain-chat': typeof LangchainChatRoute
  '/profile': typeof ProfileRoute
  '/assistants/$assistantId': typeof AssistantsAssistantIdRoute
  '/assistants/new': typeof AssistantsNewRoute
  '/knowledge/$knowledgeSourceId': typeof KnowledgeKnowledgeSourceIdRoute
  '/knowledge/auth-google': typeof KnowledgeAuthGoogleRoute
  '/knowledge/new': typeof KnowledgeNewRoute
  '/assistants': typeof AssistantsIndexRoute
  '/knowledge': typeof KnowledgeIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/langchain-chat': typeof LangchainChatRoute
  '/profile': typeof ProfileRoute
  '/assistants/$assistantId': typeof AssistantsAssistantIdRoute
  '/assistants/new': typeof AssistantsNewRoute
  '/knowledge/$knowledgeSourceId': typeof KnowledgeKnowledgeSourceIdRoute
  '/knowledge/auth-google': typeof KnowledgeAuthGoogleRoute
  '/knowledge/new': typeof KnowledgeNewRoute
  '/assistants': typeof AssistantsIndexRoute
  '/knowledge': typeof KnowledgeIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/langchain-chat': typeof LangchainChatRoute
  '/profile': typeof ProfileRoute
  '/assistants/$assistantId': typeof AssistantsAssistantIdRoute
  '/assistants/new': typeof AssistantsNewRoute
  '/knowledge/$knowledgeSourceId': typeof KnowledgeKnowledgeSourceIdRoute
  '/knowledge/auth-google': typeof KnowledgeAuthGoogleRoute
  '/knowledge/new': typeof KnowledgeNewRoute
  '/assistants/': typeof AssistantsIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/langchain-chat'
    | '/profile'
    | '/assistants/$assistantId'
    | '/assistants/new'
    | '/knowledge/$knowledgeSourceId'
    | '/knowledge/auth-google'
    | '/knowledge/new'
    | '/assistants'
    | '/knowledge'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/langchain-chat'
    | '/profile'
    | '/assistants/$assistantId'
    | '/assistants/new'
    | '/knowledge/$knowledgeSourceId'
    | '/knowledge/auth-google'
    | '/knowledge/new'
    | '/assistants'
    | '/knowledge'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/langchain-chat'
    | '/profile'
    | '/assistants/$assistantId'
    | '/assistants/new'
    | '/knowledge/$knowledgeSourceId'
    | '/knowledge/auth-google'
    | '/knowledge/new'
    | '/assistants/'
    | '/knowledge/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  LangchainChatRoute: typeof LangchainChatRoute
  ProfileRoute: typeof ProfileRoute
  AssistantsAssistantIdRoute: typeof AssistantsAssistantIdRoute
  AssistantsNewRoute: typeof AssistantsNewRoute
  KnowledgeKnowledgeSourceIdRoute: typeof KnowledgeKnowledgeSourceIdRoute
  KnowledgeAuthGoogleRoute: typeof KnowledgeAuthGoogleRoute
  KnowledgeNewRoute: typeof KnowledgeNewRoute
  AssistantsIndexRoute: typeof AssistantsIndexRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  LangchainChatRoute: LangchainChatRoute,
  ProfileRoute: ProfileRoute,
  AssistantsAssistantIdRoute: AssistantsAssistantIdRoute,
  AssistantsNewRoute: AssistantsNewRoute,
  KnowledgeKnowledgeSourceIdRoute: KnowledgeKnowledgeSourceIdRoute,
  KnowledgeAuthGoogleRoute: KnowledgeAuthGoogleRoute,
  KnowledgeNewRoute: KnowledgeNewRoute,
  AssistantsIndexRoute: AssistantsIndexRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/contact",
        "/langchain-chat",
        "/profile",
        "/assistants/$assistantId",
        "/assistants/new",
        "/knowledge/$knowledgeSourceId",
        "/knowledge/auth-google",
        "/knowledge/new",
        "/assistants/",
        "/knowledge/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/contact": {
      "filePath": "contact.tsx"
    },
    "/langchain-chat": {
      "filePath": "langchain-chat.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/assistants/$assistantId": {
      "filePath": "assistants/$assistantId.tsx"
    },
    "/assistants/new": {
      "filePath": "assistants/new.tsx"
    },
    "/knowledge/$knowledgeSourceId": {
      "filePath": "knowledge/$knowledgeSourceId.tsx"
    },
    "/knowledge/auth-google": {
      "filePath": "knowledge/auth-google.tsx"
    },
    "/knowledge/new": {
      "filePath": "knowledge/new.tsx"
    },
    "/assistants/": {
      "filePath": "assistants/index.tsx"
    },
    "/knowledge/": {
      "filePath": "knowledge/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
