/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as ContactImport } from './routes/contact'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticatedProfileIndexImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedLibrariesIndexImport } from './routes/_authenticated/libraries/index'
import { Route as AuthenticatedAssistantsIndexImport } from './routes/_authenticated/assistants/index'
import { Route as AuthenticatedLibrariesAuthGoogleImport } from './routes/_authenticated/libraries/auth-google'
import { Route as AuthenticatedLibrariesLibraryIdImport } from './routes/_authenticated/libraries/$libraryId'
import { Route as AuthenticatedConversationsSplatImport } from './routes/_authenticated/conversations/$'
import { Route as AuthenticatedAssistantsAssistantIdImport } from './routes/_authenticated/assistants/$assistantId'
import { Route as AuthenticatedProfileProfileIdConfirmImport } from './routes/_authenticated/profile/$profileId.confirm'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ContactRoute = ContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedProfileIndexRoute = AuthenticatedProfileIndexImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedLibrariesIndexRoute =
  AuthenticatedLibrariesIndexImport.update({
    id: '/libraries/',
    path: '/libraries/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedAssistantsIndexRoute =
  AuthenticatedAssistantsIndexImport.update({
    id: '/assistants/',
    path: '/assistants/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedLibrariesAuthGoogleRoute =
  AuthenticatedLibrariesAuthGoogleImport.update({
    id: '/libraries/auth-google',
    path: '/libraries/auth-google',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedLibrariesLibraryIdRoute =
  AuthenticatedLibrariesLibraryIdImport.update({
    id: '/libraries/$libraryId',
    path: '/libraries/$libraryId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedConversationsSplatRoute =
  AuthenticatedConversationsSplatImport.update({
    id: '/conversations/$',
    path: '/conversations/$',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedAssistantsAssistantIdRoute =
  AuthenticatedAssistantsAssistantIdImport.update({
    id: '/assistants/$assistantId',
    path: '/assistants/$assistantId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedProfileProfileIdConfirmRoute =
  AuthenticatedProfileProfileIdConfirmImport.update({
    id: '/profile/$profileId/confirm',
    path: '/profile/$profileId/confirm',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/assistants/$assistantId': {
      id: '/_authenticated/assistants/$assistantId'
      path: '/assistants/$assistantId'
      fullPath: '/assistants/$assistantId'
      preLoaderRoute: typeof AuthenticatedAssistantsAssistantIdImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/conversations/$': {
      id: '/_authenticated/conversations/$'
      path: '/conversations/$'
      fullPath: '/conversations/$'
      preLoaderRoute: typeof AuthenticatedConversationsSplatImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/libraries/$libraryId': {
      id: '/_authenticated/libraries/$libraryId'
      path: '/libraries/$libraryId'
      fullPath: '/libraries/$libraryId'
      preLoaderRoute: typeof AuthenticatedLibrariesLibraryIdImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/libraries/auth-google': {
      id: '/_authenticated/libraries/auth-google'
      path: '/libraries/auth-google'
      fullPath: '/libraries/auth-google'
      preLoaderRoute: typeof AuthenticatedLibrariesAuthGoogleImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/assistants/': {
      id: '/_authenticated/assistants/'
      path: '/assistants'
      fullPath: '/assistants'
      preLoaderRoute: typeof AuthenticatedAssistantsIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/libraries/': {
      id: '/_authenticated/libraries/'
      path: '/libraries'
      fullPath: '/libraries'
      preLoaderRoute: typeof AuthenticatedLibrariesIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/profile/$profileId/confirm': {
      id: '/_authenticated/profile/$profileId/confirm'
      path: '/profile/$profileId/confirm'
      fullPath: '/profile/$profileId/confirm'
      preLoaderRoute: typeof AuthenticatedProfileProfileIdConfirmImport
      parentRoute: typeof AuthenticatedRouteImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssistantsAssistantIdRoute: typeof AuthenticatedAssistantsAssistantIdRoute
  AuthenticatedConversationsSplatRoute: typeof AuthenticatedConversationsSplatRoute
  AuthenticatedLibrariesLibraryIdRoute: typeof AuthenticatedLibrariesLibraryIdRoute
  AuthenticatedLibrariesAuthGoogleRoute: typeof AuthenticatedLibrariesAuthGoogleRoute
  AuthenticatedAssistantsIndexRoute: typeof AuthenticatedAssistantsIndexRoute
  AuthenticatedLibrariesIndexRoute: typeof AuthenticatedLibrariesIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedProfileProfileIdConfirmRoute: typeof AuthenticatedProfileProfileIdConfirmRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssistantsAssistantIdRoute:
    AuthenticatedAssistantsAssistantIdRoute,
  AuthenticatedConversationsSplatRoute: AuthenticatedConversationsSplatRoute,
  AuthenticatedLibrariesLibraryIdRoute: AuthenticatedLibrariesLibraryIdRoute,
  AuthenticatedLibrariesAuthGoogleRoute: AuthenticatedLibrariesAuthGoogleRoute,
  AuthenticatedAssistantsIndexRoute: AuthenticatedAssistantsIndexRoute,
  AuthenticatedLibrariesIndexRoute: AuthenticatedLibrariesIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedProfileProfileIdConfirmRoute:
    AuthenticatedProfileProfileIdConfirmRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/assistants/$assistantId': typeof AuthenticatedAssistantsAssistantIdRoute
  '/conversations/$': typeof AuthenticatedConversationsSplatRoute
  '/libraries/$libraryId': typeof AuthenticatedLibrariesLibraryIdRoute
  '/libraries/auth-google': typeof AuthenticatedLibrariesAuthGoogleRoute
  '/assistants': typeof AuthenticatedAssistantsIndexRoute
  '/libraries': typeof AuthenticatedLibrariesIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/profile/$profileId/confirm': typeof AuthenticatedProfileProfileIdConfirmRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/assistants/$assistantId': typeof AuthenticatedAssistantsAssistantIdRoute
  '/conversations/$': typeof AuthenticatedConversationsSplatRoute
  '/libraries/$libraryId': typeof AuthenticatedLibrariesLibraryIdRoute
  '/libraries/auth-google': typeof AuthenticatedLibrariesAuthGoogleRoute
  '/assistants': typeof AuthenticatedAssistantsIndexRoute
  '/libraries': typeof AuthenticatedLibrariesIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/profile/$profileId/confirm': typeof AuthenticatedProfileProfileIdConfirmRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/_authenticated/assistants/$assistantId': typeof AuthenticatedAssistantsAssistantIdRoute
  '/_authenticated/conversations/$': typeof AuthenticatedConversationsSplatRoute
  '/_authenticated/libraries/$libraryId': typeof AuthenticatedLibrariesLibraryIdRoute
  '/_authenticated/libraries/auth-google': typeof AuthenticatedLibrariesAuthGoogleRoute
  '/_authenticated/assistants/': typeof AuthenticatedAssistantsIndexRoute
  '/_authenticated/libraries/': typeof AuthenticatedLibrariesIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/profile/$profileId/confirm': typeof AuthenticatedProfileProfileIdConfirmRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/contact'
    | '/login'
    | '/assistants/$assistantId'
    | '/conversations/$'
    | '/libraries/$libraryId'
    | '/libraries/auth-google'
    | '/assistants'
    | '/libraries'
    | '/profile'
    | '/profile/$profileId/confirm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/contact'
    | '/login'
    | '/assistants/$assistantId'
    | '/conversations/$'
    | '/libraries/$libraryId'
    | '/libraries/auth-google'
    | '/assistants'
    | '/libraries'
    | '/profile'
    | '/profile/$profileId/confirm'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/contact'
    | '/login'
    | '/_authenticated/assistants/$assistantId'
    | '/_authenticated/conversations/$'
    | '/_authenticated/libraries/$libraryId'
    | '/_authenticated/libraries/auth-google'
    | '/_authenticated/assistants/'
    | '/_authenticated/libraries/'
    | '/_authenticated/profile/'
    | '/_authenticated/profile/$profileId/confirm'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/contact",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated/route.tsx",
      "children": [
        "/_authenticated/assistants/$assistantId",
        "/_authenticated/conversations/$",
        "/_authenticated/libraries/$libraryId",
        "/_authenticated/libraries/auth-google",
        "/_authenticated/assistants/",
        "/_authenticated/libraries/",
        "/_authenticated/profile/",
        "/_authenticated/profile/$profileId/confirm"
      ]
    },
    "/contact": {
      "filePath": "contact.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_authenticated/assistants/$assistantId": {
      "filePath": "_authenticated/assistants/$assistantId.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/conversations/$": {
      "filePath": "_authenticated/conversations/$.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/libraries/$libraryId": {
      "filePath": "_authenticated/libraries/$libraryId.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/libraries/auth-google": {
      "filePath": "_authenticated/libraries/auth-google.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/assistants/": {
      "filePath": "_authenticated/assistants/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/libraries/": {
      "filePath": "_authenticated/libraries/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/profile/": {
      "filePath": "_authenticated/profile/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/profile/$profileId/confirm": {
      "filePath": "_authenticated/profile/$profileId.confirm.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
