/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProfileImport } from './routes/profile'
import { Route as LangchainChatImport } from './routes/langchain-chat'
import { Route as ContactImport } from './routes/contact'
import { Route as IndexImport } from './routes/index'
import { Route as LibrariesIndexImport } from './routes/libraries/index'
import { Route as AssistantsIndexImport } from './routes/assistants/index'
import { Route as LibrariesNewImport } from './routes/libraries/new'
import { Route as LibrariesAuthGoogleImport } from './routes/libraries/auth-google'
import { Route as LibrariesLibraryIdImport } from './routes/libraries/$libraryId'
import { Route as AssistantsNewImport } from './routes/assistants/new'
import { Route as AssistantsAssistantIdImport } from './routes/assistants/$assistantId'

// Create/Update Routes

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const LangchainChatRoute = LangchainChatImport.update({
  id: '/langchain-chat',
  path: '/langchain-chat',
  getParentRoute: () => rootRoute,
} as any)

const ContactRoute = ContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LibrariesIndexRoute = LibrariesIndexImport.update({
  id: '/libraries/',
  path: '/libraries/',
  getParentRoute: () => rootRoute,
} as any)

const AssistantsIndexRoute = AssistantsIndexImport.update({
  id: '/assistants/',
  path: '/assistants/',
  getParentRoute: () => rootRoute,
} as any)

const LibrariesNewRoute = LibrariesNewImport.update({
  id: '/libraries/new',
  path: '/libraries/new',
  getParentRoute: () => rootRoute,
} as any)

const LibrariesAuthGoogleRoute = LibrariesAuthGoogleImport.update({
  id: '/libraries/auth-google',
  path: '/libraries/auth-google',
  getParentRoute: () => rootRoute,
} as any)

const LibrariesLibraryIdRoute = LibrariesLibraryIdImport.update({
  id: '/libraries/$libraryId',
  path: '/libraries/$libraryId',
  getParentRoute: () => rootRoute,
} as any)

const AssistantsNewRoute = AssistantsNewImport.update({
  id: '/assistants/new',
  path: '/assistants/new',
  getParentRoute: () => rootRoute,
} as any)

const AssistantsAssistantIdRoute = AssistantsAssistantIdImport.update({
  id: '/assistants/$assistantId',
  path: '/assistants/$assistantId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/langchain-chat': {
      id: '/langchain-chat'
      path: '/langchain-chat'
      fullPath: '/langchain-chat'
      preLoaderRoute: typeof LangchainChatImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/assistants/$assistantId': {
      id: '/assistants/$assistantId'
      path: '/assistants/$assistantId'
      fullPath: '/assistants/$assistantId'
      preLoaderRoute: typeof AssistantsAssistantIdImport
      parentRoute: typeof rootRoute
    }
    '/assistants/new': {
      id: '/assistants/new'
      path: '/assistants/new'
      fullPath: '/assistants/new'
      preLoaderRoute: typeof AssistantsNewImport
      parentRoute: typeof rootRoute
    }
    '/libraries/$libraryId': {
      id: '/libraries/$libraryId'
      path: '/libraries/$libraryId'
      fullPath: '/libraries/$libraryId'
      preLoaderRoute: typeof LibrariesLibraryIdImport
      parentRoute: typeof rootRoute
    }
    '/libraries/auth-google': {
      id: '/libraries/auth-google'
      path: '/libraries/auth-google'
      fullPath: '/libraries/auth-google'
      preLoaderRoute: typeof LibrariesAuthGoogleImport
      parentRoute: typeof rootRoute
    }
    '/libraries/new': {
      id: '/libraries/new'
      path: '/libraries/new'
      fullPath: '/libraries/new'
      preLoaderRoute: typeof LibrariesNewImport
      parentRoute: typeof rootRoute
    }
    '/assistants/': {
      id: '/assistants/'
      path: '/assistants'
      fullPath: '/assistants'
      preLoaderRoute: typeof AssistantsIndexImport
      parentRoute: typeof rootRoute
    }
    '/libraries/': {
      id: '/libraries/'
      path: '/libraries'
      fullPath: '/libraries'
      preLoaderRoute: typeof LibrariesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/langchain-chat': typeof LangchainChatRoute
  '/profile': typeof ProfileRoute
  '/assistants/$assistantId': typeof AssistantsAssistantIdRoute
  '/assistants/new': typeof AssistantsNewRoute
  '/libraries/$libraryId': typeof LibrariesLibraryIdRoute
  '/libraries/auth-google': typeof LibrariesAuthGoogleRoute
  '/libraries/new': typeof LibrariesNewRoute
  '/assistants': typeof AssistantsIndexRoute
  '/libraries': typeof LibrariesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/langchain-chat': typeof LangchainChatRoute
  '/profile': typeof ProfileRoute
  '/assistants/$assistantId': typeof AssistantsAssistantIdRoute
  '/assistants/new': typeof AssistantsNewRoute
  '/libraries/$libraryId': typeof LibrariesLibraryIdRoute
  '/libraries/auth-google': typeof LibrariesAuthGoogleRoute
  '/libraries/new': typeof LibrariesNewRoute
  '/assistants': typeof AssistantsIndexRoute
  '/libraries': typeof LibrariesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/langchain-chat': typeof LangchainChatRoute
  '/profile': typeof ProfileRoute
  '/assistants/$assistantId': typeof AssistantsAssistantIdRoute
  '/assistants/new': typeof AssistantsNewRoute
  '/libraries/$libraryId': typeof LibrariesLibraryIdRoute
  '/libraries/auth-google': typeof LibrariesAuthGoogleRoute
  '/libraries/new': typeof LibrariesNewRoute
  '/assistants/': typeof AssistantsIndexRoute
  '/libraries/': typeof LibrariesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/langchain-chat'
    | '/profile'
    | '/assistants/$assistantId'
    | '/assistants/new'
    | '/libraries/$libraryId'
    | '/libraries/auth-google'
    | '/libraries/new'
    | '/assistants'
    | '/libraries'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/langchain-chat'
    | '/profile'
    | '/assistants/$assistantId'
    | '/assistants/new'
    | '/libraries/$libraryId'
    | '/libraries/auth-google'
    | '/libraries/new'
    | '/assistants'
    | '/libraries'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/langchain-chat'
    | '/profile'
    | '/assistants/$assistantId'
    | '/assistants/new'
    | '/libraries/$libraryId'
    | '/libraries/auth-google'
    | '/libraries/new'
    | '/assistants/'
    | '/libraries/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  LangchainChatRoute: typeof LangchainChatRoute
  ProfileRoute: typeof ProfileRoute
  AssistantsAssistantIdRoute: typeof AssistantsAssistantIdRoute
  AssistantsNewRoute: typeof AssistantsNewRoute
  LibrariesLibraryIdRoute: typeof LibrariesLibraryIdRoute
  LibrariesAuthGoogleRoute: typeof LibrariesAuthGoogleRoute
  LibrariesNewRoute: typeof LibrariesNewRoute
  AssistantsIndexRoute: typeof AssistantsIndexRoute
  LibrariesIndexRoute: typeof LibrariesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  LangchainChatRoute: LangchainChatRoute,
  ProfileRoute: ProfileRoute,
  AssistantsAssistantIdRoute: AssistantsAssistantIdRoute,
  AssistantsNewRoute: AssistantsNewRoute,
  LibrariesLibraryIdRoute: LibrariesLibraryIdRoute,
  LibrariesAuthGoogleRoute: LibrariesAuthGoogleRoute,
  LibrariesNewRoute: LibrariesNewRoute,
  AssistantsIndexRoute: AssistantsIndexRoute,
  LibrariesIndexRoute: LibrariesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/contact",
        "/langchain-chat",
        "/profile",
        "/assistants/$assistantId",
        "/assistants/new",
        "/libraries/$libraryId",
        "/libraries/auth-google",
        "/libraries/new",
        "/assistants/",
        "/libraries/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/contact": {
      "filePath": "contact.tsx"
    },
    "/langchain-chat": {
      "filePath": "langchain-chat.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/assistants/$assistantId": {
      "filePath": "assistants/$assistantId.tsx"
    },
    "/assistants/new": {
      "filePath": "assistants/new.tsx"
    },
    "/libraries/$libraryId": {
      "filePath": "libraries/$libraryId.tsx"
    },
    "/libraries/auth-google": {
      "filePath": "libraries/auth-google.tsx"
    },
    "/libraries/new": {
      "filePath": "libraries/new.tsx"
    },
    "/assistants/": {
      "filePath": "assistants/index.tsx"
    },
    "/libraries/": {
      "filePath": "libraries/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
