export const queryKeys = {
  UserDashboard: 'UserDashboard',
  AiAssistant: 'AiAssistant',
  AiAssistants: 'AiAssistants',
  AiLibrary: 'AiLibrary',
  AiLibraries: 'AiLibraries',
  AiList: 'AiList',
  AiLists: 'AiLists',
  AiLibraryFiles: 'AiLibraryFiles',
  GoogleDriveFiles: 'GoogleDriveFiles',
  Conversations: 'Conversations',
  Conversation: 'Conversation',
  Language: 'Language',
  Theme: 'Theme',
  User: 'User',
  Users: 'Users',
  ConversationInvitation: 'ConversationInvitation',
  BackendUrl: 'BackendUrl',
  UserProfile: 'UserProfile',
}
