/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedConversationsRouteRouteImport } from './routes/_authenticated/conversations/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedListsIndexRouteImport } from './routes/_authenticated/lists/index'
import { Route as AuthenticatedLibrariesIndexRouteImport } from './routes/_authenticated/libraries/index'
import { Route as AuthenticatedConversationsIndexRouteImport } from './routes/_authenticated/conversations/index'
import { Route as AuthenticatedAssistantsIndexRouteImport } from './routes/_authenticated/assistants/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedLibrariesAuthGoogleRouteImport } from './routes/_authenticated/libraries/auth-google'
import { Route as AuthenticatedConversationsConversationIdRouteImport } from './routes/_authenticated/conversations/$conversationId'
import { Route as AuthenticatedAssistantsAssistantIdRouteImport } from './routes/_authenticated/assistants/$assistantId'
import { Route as AuthenticatedAdminQueuesRouteImport } from './routes/_authenticated/admin/queues'
import { Route as AuthenticatedAdminAiServicesRouteImport } from './routes/_authenticated/admin/ai-services'
import { Route as AuthenticatedListsListIdRouteRouteImport } from './routes/_authenticated/lists/$listId/route'
import { Route as AuthenticatedLibrariesLibraryIdRouteRouteImport } from './routes/_authenticated/libraries/$libraryId/route'
import { Route as AuthenticatedListsListIdIndexRouteImport } from './routes/_authenticated/lists/$listId/index'
import { Route as AuthenticatedLibrariesLibraryIdIndexRouteImport } from './routes/_authenticated/libraries/$libraryId/index'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin/users/index'
import { Route as AuthenticatedProfileProfileIdConfirmRouteImport } from './routes/_authenticated/profile/$profileId.confirm'
import { Route as AuthenticatedProfileProfileIdAdminConfirmRouteImport } from './routes/_authenticated/profile/$profileId.admin-confirm'
import { Route as AuthenticatedListsListIdStatisticsRouteImport } from './routes/_authenticated/lists/$listId/statistics'
import { Route as AuthenticatedListsListIdEnrichmentsRouteImport } from './routes/_authenticated/lists/$listId/enrichments'
import { Route as AuthenticatedListsListIdEditRouteImport } from './routes/_authenticated/lists/$listId/edit'
import { Route as AuthenticatedLibrariesLibraryIdUpdatesRouteImport } from './routes/_authenticated/libraries/$libraryId/updates'
import { Route as AuthenticatedLibrariesLibraryIdSettingsRouteImport } from './routes/_authenticated/libraries/$libraryId/settings'
import { Route as AuthenticatedLibrariesLibraryIdQueryRouteImport } from './routes/_authenticated/libraries/$libraryId/query'
import { Route as AuthenticatedLibrariesLibraryIdProcessingRouteImport } from './routes/_authenticated/libraries/$libraryId/processing'
import { Route as AuthenticatedLibrariesLibraryIdPostprocessRouteImport } from './routes/_authenticated/libraries/$libraryId/postprocess'
import { Route as AuthenticatedAdminUsersUserIdRouteImport } from './routes/_authenticated/admin/users/$userId'
import { Route as AuthenticatedLibrariesLibraryIdCrawlersRouteRouteImport } from './routes/_authenticated/libraries/$libraryId/crawlers/route'
import { Route as AuthenticatedLibrariesLibraryIdFilesIndexRouteImport } from './routes/_authenticated/libraries/$libraryId/files/index'
import { Route as AuthenticatedLibrariesLibraryIdCrawlersIndexRouteImport } from './routes/_authenticated/libraries/$libraryId/crawlers/index'
import { Route as AuthenticatedConversationsConversationIdConfirmInvitationInvitationIdRouteImport } from './routes/_authenticated/conversations/$conversationId_.confirm-invitation.$invitationId'
import { Route as AuthenticatedLibrariesLibraryIdFilesFileIdRouteRouteImport } from './routes/_authenticated/libraries/$libraryId/files/$fileId/route'
import { Route as AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRouteRouteImport } from './routes/_authenticated/libraries/$libraryId/crawlers/$crawlerId/route'
import { Route as AuthenticatedLibrariesLibraryIdFilesFileIdIndexRouteImport } from './routes/_authenticated/libraries/$libraryId/files/$fileId/index'
import { Route as AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdIndexRouteImport } from './routes/_authenticated/libraries/$libraryId/crawlers/$crawlerId/index'
import { Route as AuthenticatedLibrariesLibraryIdFilesFileIdTasksRouteImport } from './routes/_authenticated/libraries/$libraryId/files/$fileId/tasks'
import { Route as AuthenticatedLibrariesLibraryIdFilesFileIdSimilarityRouteImport } from './routes/_authenticated/libraries/$libraryId/files/$fileId/similarity'
import { Route as AuthenticatedLibrariesLibraryIdFilesFileIdChunksRouteImport } from './routes/_authenticated/libraries/$libraryId/files/$fileId/chunks'
import { Route as AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsRouteRouteImport } from './routes/_authenticated/libraries/$libraryId/crawlers/$crawlerId/runs/route'
import { Route as AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsIndexRouteImport } from './routes/_authenticated/libraries/$libraryId/crawlers/$crawlerId/runs/index'
import { Route as AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsCrawlerRunIdRouteImport } from './routes/_authenticated/libraries/$libraryId/crawlers/$crawlerId/runs/$crawlerRunId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConversationsRouteRoute =
  AuthenticatedConversationsRouteRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedListsIndexRoute = AuthenticatedListsIndexRouteImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibrariesIndexRoute =
  AuthenticatedLibrariesIndexRouteImport.update({
    id: '/libraries/',
    path: '/libraries/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConversationsIndexRoute =
  AuthenticatedConversationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConversationsRouteRoute,
  } as any)
const AuthenticatedAssistantsIndexRoute =
  AuthenticatedAssistantsIndexRouteImport.update({
    id: '/assistants/',
    path: '/assistants/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedLibrariesAuthGoogleRoute =
  AuthenticatedLibrariesAuthGoogleRouteImport.update({
    id: '/libraries/auth-google',
    path: '/libraries/auth-google',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConversationsConversationIdRoute =
  AuthenticatedConversationsConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthenticatedConversationsRouteRoute,
  } as any)
const AuthenticatedAssistantsAssistantIdRoute =
  AuthenticatedAssistantsAssistantIdRouteImport.update({
    id: '/assistants/$assistantId',
    path: '/assistants/$assistantId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminQueuesRoute =
  AuthenticatedAdminQueuesRouteImport.update({
    id: '/queues',
    path: '/queues',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAiServicesRoute =
  AuthenticatedAdminAiServicesRouteImport.update({
    id: '/ai-services',
    path: '/ai-services',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedListsListIdRouteRoute =
  AuthenticatedListsListIdRouteRouteImport.update({
    id: '/lists/$listId',
    path: '/lists/$listId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLibrariesLibraryIdRouteRoute =
  AuthenticatedLibrariesLibraryIdRouteRouteImport.update({
    id: '/libraries/$libraryId',
    path: '/libraries/$libraryId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedListsListIdIndexRoute =
  AuthenticatedListsListIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedListsListIdRouteRoute,
  } as any)
const AuthenticatedLibrariesLibraryIdIndexRoute =
  AuthenticatedLibrariesLibraryIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLibrariesLibraryIdRouteRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedProfileProfileIdConfirmRoute =
  AuthenticatedProfileProfileIdConfirmRouteImport.update({
    id: '/profile/$profileId/confirm',
    path: '/profile/$profileId/confirm',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileProfileIdAdminConfirmRoute =
  AuthenticatedProfileProfileIdAdminConfirmRouteImport.update({
    id: '/profile/$profileId/admin-confirm',
    path: '/profile/$profileId/admin-confirm',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedListsListIdStatisticsRoute =
  AuthenticatedListsListIdStatisticsRouteImport.update({
    id: '/statistics',
    path: '/statistics',
    getParentRoute: () => AuthenticatedListsListIdRouteRoute,
  } as any)
const AuthenticatedListsListIdEnrichmentsRoute =
  AuthenticatedListsListIdEnrichmentsRouteImport.update({
    id: '/enrichments',
    path: '/enrichments',
    getParentRoute: () => AuthenticatedListsListIdRouteRoute,
  } as any)
const AuthenticatedListsListIdEditRoute =
  AuthenticatedListsListIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedListsListIdRouteRoute,
  } as any)
const AuthenticatedLibrariesLibraryIdUpdatesRoute =
  AuthenticatedLibrariesLibraryIdUpdatesRouteImport.update({
    id: '/updates',
    path: '/updates',
    getParentRoute: () => AuthenticatedLibrariesLibraryIdRouteRoute,
  } as any)
const AuthenticatedLibrariesLibraryIdSettingsRoute =
  AuthenticatedLibrariesLibraryIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedLibrariesLibraryIdRouteRoute,
  } as any)
const AuthenticatedLibrariesLibraryIdQueryRoute =
  AuthenticatedLibrariesLibraryIdQueryRouteImport.update({
    id: '/query',
    path: '/query',
    getParentRoute: () => AuthenticatedLibrariesLibraryIdRouteRoute,
  } as any)
const AuthenticatedLibrariesLibraryIdProcessingRoute =
  AuthenticatedLibrariesLibraryIdProcessingRouteImport.update({
    id: '/processing',
    path: '/processing',
    getParentRoute: () => AuthenticatedLibrariesLibraryIdRouteRoute,
  } as any)
const AuthenticatedLibrariesLibraryIdPostprocessRoute =
  AuthenticatedLibrariesLibraryIdPostprocessRouteImport.update({
    id: '/postprocess',
    path: '/postprocess',
    getParentRoute: () => AuthenticatedLibrariesLibraryIdRouteRoute,
  } as any)
const AuthenticatedAdminUsersUserIdRoute =
  AuthenticatedAdminUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedLibrariesLibraryIdCrawlersRouteRoute =
  AuthenticatedLibrariesLibraryIdCrawlersRouteRouteImport.update({
    id: '/crawlers',
    path: '/crawlers',
    getParentRoute: () => AuthenticatedLibrariesLibraryIdRouteRoute,
  } as any)
const AuthenticatedLibrariesLibraryIdFilesIndexRoute =
  AuthenticatedLibrariesLibraryIdFilesIndexRouteImport.update({
    id: '/files/',
    path: '/files/',
    getParentRoute: () => AuthenticatedLibrariesLibraryIdRouteRoute,
  } as any)
const AuthenticatedLibrariesLibraryIdCrawlersIndexRoute =
  AuthenticatedLibrariesLibraryIdCrawlersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLibrariesLibraryIdCrawlersRouteRoute,
  } as any)
const AuthenticatedConversationsConversationIdConfirmInvitationInvitationIdRoute =
  AuthenticatedConversationsConversationIdConfirmInvitationInvitationIdRouteImport.update(
    {
      id: '/$conversationId_/confirm-invitation/$invitationId',
      path: '/$conversationId/confirm-invitation/$invitationId',
      getParentRoute: () => AuthenticatedConversationsRouteRoute,
    } as any,
  )
const AuthenticatedLibrariesLibraryIdFilesFileIdRouteRoute =
  AuthenticatedLibrariesLibraryIdFilesFileIdRouteRouteImport.update({
    id: '/files/$fileId',
    path: '/files/$fileId',
    getParentRoute: () => AuthenticatedLibrariesLibraryIdRouteRoute,
  } as any)
const AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRouteRoute =
  AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRouteRouteImport.update({
    id: '/$crawlerId',
    path: '/$crawlerId',
    getParentRoute: () => AuthenticatedLibrariesLibraryIdCrawlersRouteRoute,
  } as any)
const AuthenticatedLibrariesLibraryIdFilesFileIdIndexRoute =
  AuthenticatedLibrariesLibraryIdFilesFileIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLibrariesLibraryIdFilesFileIdRouteRoute,
  } as any)
const AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdIndexRoute =
  AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRouteRoute,
  } as any)
const AuthenticatedLibrariesLibraryIdFilesFileIdTasksRoute =
  AuthenticatedLibrariesLibraryIdFilesFileIdTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AuthenticatedLibrariesLibraryIdFilesFileIdRouteRoute,
  } as any)
const AuthenticatedLibrariesLibraryIdFilesFileIdSimilarityRoute =
  AuthenticatedLibrariesLibraryIdFilesFileIdSimilarityRouteImport.update({
    id: '/similarity',
    path: '/similarity',
    getParentRoute: () => AuthenticatedLibrariesLibraryIdFilesFileIdRouteRoute,
  } as any)
const AuthenticatedLibrariesLibraryIdFilesFileIdChunksRoute =
  AuthenticatedLibrariesLibraryIdFilesFileIdChunksRouteImport.update({
    id: '/chunks',
    path: '/chunks',
    getParentRoute: () => AuthenticatedLibrariesLibraryIdFilesFileIdRouteRoute,
  } as any)
const AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsRouteRoute =
  AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsRouteRouteImport.update({
    id: '/runs',
    path: '/runs',
    getParentRoute: () =>
      AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRouteRoute,
  } as any)
const AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsIndexRoute =
  AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsRouteRoute,
  } as any)
const AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsCrawlerRunIdRoute =
  AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsCrawlerRunIdRouteImport.update(
    {
      id: '/$crawlerRunId',
      path: '/$crawlerRunId',
      getParentRoute: () =>
        AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/conversations': typeof AuthenticatedConversationsRouteRouteWithChildren
  '/libraries/$libraryId': typeof AuthenticatedLibrariesLibraryIdRouteRouteWithChildren
  '/lists/$listId': typeof AuthenticatedListsListIdRouteRouteWithChildren
  '/admin/ai-services': typeof AuthenticatedAdminAiServicesRoute
  '/admin/queues': typeof AuthenticatedAdminQueuesRoute
  '/assistants/$assistantId': typeof AuthenticatedAssistantsAssistantIdRoute
  '/conversations/$conversationId': typeof AuthenticatedConversationsConversationIdRoute
  '/libraries/auth-google': typeof AuthenticatedLibrariesAuthGoogleRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/assistants': typeof AuthenticatedAssistantsIndexRoute
  '/conversations/': typeof AuthenticatedConversationsIndexRoute
  '/libraries': typeof AuthenticatedLibrariesIndexRoute
  '/lists': typeof AuthenticatedListsIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/libraries/$libraryId/crawlers': typeof AuthenticatedLibrariesLibraryIdCrawlersRouteRouteWithChildren
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/libraries/$libraryId/postprocess': typeof AuthenticatedLibrariesLibraryIdPostprocessRoute
  '/libraries/$libraryId/processing': typeof AuthenticatedLibrariesLibraryIdProcessingRoute
  '/libraries/$libraryId/query': typeof AuthenticatedLibrariesLibraryIdQueryRoute
  '/libraries/$libraryId/settings': typeof AuthenticatedLibrariesLibraryIdSettingsRoute
  '/libraries/$libraryId/updates': typeof AuthenticatedLibrariesLibraryIdUpdatesRoute
  '/lists/$listId/edit': typeof AuthenticatedListsListIdEditRoute
  '/lists/$listId/enrichments': typeof AuthenticatedListsListIdEnrichmentsRoute
  '/lists/$listId/statistics': typeof AuthenticatedListsListIdStatisticsRoute
  '/profile/$profileId/admin-confirm': typeof AuthenticatedProfileProfileIdAdminConfirmRoute
  '/profile/$profileId/confirm': typeof AuthenticatedProfileProfileIdConfirmRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/libraries/$libraryId/': typeof AuthenticatedLibrariesLibraryIdIndexRoute
  '/lists/$listId/': typeof AuthenticatedListsListIdIndexRoute
  '/libraries/$libraryId/crawlers/$crawlerId': typeof AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRouteRouteWithChildren
  '/libraries/$libraryId/files/$fileId': typeof AuthenticatedLibrariesLibraryIdFilesFileIdRouteRouteWithChildren
  '/conversations/$conversationId/confirm-invitation/$invitationId': typeof AuthenticatedConversationsConversationIdConfirmInvitationInvitationIdRoute
  '/libraries/$libraryId/crawlers/': typeof AuthenticatedLibrariesLibraryIdCrawlersIndexRoute
  '/libraries/$libraryId/files': typeof AuthenticatedLibrariesLibraryIdFilesIndexRoute
  '/libraries/$libraryId/crawlers/$crawlerId/runs': typeof AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsRouteRouteWithChildren
  '/libraries/$libraryId/files/$fileId/chunks': typeof AuthenticatedLibrariesLibraryIdFilesFileIdChunksRoute
  '/libraries/$libraryId/files/$fileId/similarity': typeof AuthenticatedLibrariesLibraryIdFilesFileIdSimilarityRoute
  '/libraries/$libraryId/files/$fileId/tasks': typeof AuthenticatedLibrariesLibraryIdFilesFileIdTasksRoute
  '/libraries/$libraryId/crawlers/$crawlerId/': typeof AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdIndexRoute
  '/libraries/$libraryId/files/$fileId/': typeof AuthenticatedLibrariesLibraryIdFilesFileIdIndexRoute
  '/libraries/$libraryId/crawlers/$crawlerId/runs/$crawlerRunId': typeof AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsCrawlerRunIdRoute
  '/libraries/$libraryId/crawlers/$crawlerId/runs/': typeof AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/ai-services': typeof AuthenticatedAdminAiServicesRoute
  '/admin/queues': typeof AuthenticatedAdminQueuesRoute
  '/assistants/$assistantId': typeof AuthenticatedAssistantsAssistantIdRoute
  '/conversations/$conversationId': typeof AuthenticatedConversationsConversationIdRoute
  '/libraries/auth-google': typeof AuthenticatedLibrariesAuthGoogleRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/assistants': typeof AuthenticatedAssistantsIndexRoute
  '/conversations': typeof AuthenticatedConversationsIndexRoute
  '/libraries': typeof AuthenticatedLibrariesIndexRoute
  '/lists': typeof AuthenticatedListsIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/libraries/$libraryId/postprocess': typeof AuthenticatedLibrariesLibraryIdPostprocessRoute
  '/libraries/$libraryId/processing': typeof AuthenticatedLibrariesLibraryIdProcessingRoute
  '/libraries/$libraryId/query': typeof AuthenticatedLibrariesLibraryIdQueryRoute
  '/libraries/$libraryId/settings': typeof AuthenticatedLibrariesLibraryIdSettingsRoute
  '/libraries/$libraryId/updates': typeof AuthenticatedLibrariesLibraryIdUpdatesRoute
  '/lists/$listId/edit': typeof AuthenticatedListsListIdEditRoute
  '/lists/$listId/enrichments': typeof AuthenticatedListsListIdEnrichmentsRoute
  '/lists/$listId/statistics': typeof AuthenticatedListsListIdStatisticsRoute
  '/profile/$profileId/admin-confirm': typeof AuthenticatedProfileProfileIdAdminConfirmRoute
  '/profile/$profileId/confirm': typeof AuthenticatedProfileProfileIdConfirmRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/libraries/$libraryId': typeof AuthenticatedLibrariesLibraryIdIndexRoute
  '/lists/$listId': typeof AuthenticatedListsListIdIndexRoute
  '/conversations/$conversationId/confirm-invitation/$invitationId': typeof AuthenticatedConversationsConversationIdConfirmInvitationInvitationIdRoute
  '/libraries/$libraryId/crawlers': typeof AuthenticatedLibrariesLibraryIdCrawlersIndexRoute
  '/libraries/$libraryId/files': typeof AuthenticatedLibrariesLibraryIdFilesIndexRoute
  '/libraries/$libraryId/files/$fileId/chunks': typeof AuthenticatedLibrariesLibraryIdFilesFileIdChunksRoute
  '/libraries/$libraryId/files/$fileId/similarity': typeof AuthenticatedLibrariesLibraryIdFilesFileIdSimilarityRoute
  '/libraries/$libraryId/files/$fileId/tasks': typeof AuthenticatedLibrariesLibraryIdFilesFileIdTasksRoute
  '/libraries/$libraryId/crawlers/$crawlerId': typeof AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdIndexRoute
  '/libraries/$libraryId/files/$fileId': typeof AuthenticatedLibrariesLibraryIdFilesFileIdIndexRoute
  '/libraries/$libraryId/crawlers/$crawlerId/runs/$crawlerRunId': typeof AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsCrawlerRunIdRoute
  '/libraries/$libraryId/crawlers/$crawlerId/runs': typeof AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/conversations': typeof AuthenticatedConversationsRouteRouteWithChildren
  '/_authenticated/libraries/$libraryId': typeof AuthenticatedLibrariesLibraryIdRouteRouteWithChildren
  '/_authenticated/lists/$listId': typeof AuthenticatedListsListIdRouteRouteWithChildren
  '/_authenticated/admin/ai-services': typeof AuthenticatedAdminAiServicesRoute
  '/_authenticated/admin/queues': typeof AuthenticatedAdminQueuesRoute
  '/_authenticated/assistants/$assistantId': typeof AuthenticatedAssistantsAssistantIdRoute
  '/_authenticated/conversations/$conversationId': typeof AuthenticatedConversationsConversationIdRoute
  '/_authenticated/libraries/auth-google': typeof AuthenticatedLibrariesAuthGoogleRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/assistants/': typeof AuthenticatedAssistantsIndexRoute
  '/_authenticated/conversations/': typeof AuthenticatedConversationsIndexRoute
  '/_authenticated/libraries/': typeof AuthenticatedLibrariesIndexRoute
  '/_authenticated/lists/': typeof AuthenticatedListsIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/libraries/$libraryId/crawlers': typeof AuthenticatedLibrariesLibraryIdCrawlersRouteRouteWithChildren
  '/_authenticated/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/_authenticated/libraries/$libraryId/postprocess': typeof AuthenticatedLibrariesLibraryIdPostprocessRoute
  '/_authenticated/libraries/$libraryId/processing': typeof AuthenticatedLibrariesLibraryIdProcessingRoute
  '/_authenticated/libraries/$libraryId/query': typeof AuthenticatedLibrariesLibraryIdQueryRoute
  '/_authenticated/libraries/$libraryId/settings': typeof AuthenticatedLibrariesLibraryIdSettingsRoute
  '/_authenticated/libraries/$libraryId/updates': typeof AuthenticatedLibrariesLibraryIdUpdatesRoute
  '/_authenticated/lists/$listId/edit': typeof AuthenticatedListsListIdEditRoute
  '/_authenticated/lists/$listId/enrichments': typeof AuthenticatedListsListIdEnrichmentsRoute
  '/_authenticated/lists/$listId/statistics': typeof AuthenticatedListsListIdStatisticsRoute
  '/_authenticated/profile/$profileId/admin-confirm': typeof AuthenticatedProfileProfileIdAdminConfirmRoute
  '/_authenticated/profile/$profileId/confirm': typeof AuthenticatedProfileProfileIdConfirmRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_authenticated/libraries/$libraryId/': typeof AuthenticatedLibrariesLibraryIdIndexRoute
  '/_authenticated/lists/$listId/': typeof AuthenticatedListsListIdIndexRoute
  '/_authenticated/libraries/$libraryId/crawlers/$crawlerId': typeof AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRouteRouteWithChildren
  '/_authenticated/libraries/$libraryId/files/$fileId': typeof AuthenticatedLibrariesLibraryIdFilesFileIdRouteRouteWithChildren
  '/_authenticated/conversations/$conversationId_/confirm-invitation/$invitationId': typeof AuthenticatedConversationsConversationIdConfirmInvitationInvitationIdRoute
  '/_authenticated/libraries/$libraryId/crawlers/': typeof AuthenticatedLibrariesLibraryIdCrawlersIndexRoute
  '/_authenticated/libraries/$libraryId/files/': typeof AuthenticatedLibrariesLibraryIdFilesIndexRoute
  '/_authenticated/libraries/$libraryId/crawlers/$crawlerId/runs': typeof AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsRouteRouteWithChildren
  '/_authenticated/libraries/$libraryId/files/$fileId/chunks': typeof AuthenticatedLibrariesLibraryIdFilesFileIdChunksRoute
  '/_authenticated/libraries/$libraryId/files/$fileId/similarity': typeof AuthenticatedLibrariesLibraryIdFilesFileIdSimilarityRoute
  '/_authenticated/libraries/$libraryId/files/$fileId/tasks': typeof AuthenticatedLibrariesLibraryIdFilesFileIdTasksRoute
  '/_authenticated/libraries/$libraryId/crawlers/$crawlerId/': typeof AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdIndexRoute
  '/_authenticated/libraries/$libraryId/files/$fileId/': typeof AuthenticatedLibrariesLibraryIdFilesFileIdIndexRoute
  '/_authenticated/libraries/$libraryId/crawlers/$crawlerId/runs/$crawlerRunId': typeof AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsCrawlerRunIdRoute
  '/_authenticated/libraries/$libraryId/crawlers/$crawlerId/runs/': typeof AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/conversations'
    | '/libraries/$libraryId'
    | '/lists/$listId'
    | '/admin/ai-services'
    | '/admin/queues'
    | '/assistants/$assistantId'
    | '/conversations/$conversationId'
    | '/libraries/auth-google'
    | '/admin/'
    | '/assistants'
    | '/conversations/'
    | '/libraries'
    | '/lists'
    | '/profile'
    | '/libraries/$libraryId/crawlers'
    | '/admin/users/$userId'
    | '/libraries/$libraryId/postprocess'
    | '/libraries/$libraryId/processing'
    | '/libraries/$libraryId/query'
    | '/libraries/$libraryId/settings'
    | '/libraries/$libraryId/updates'
    | '/lists/$listId/edit'
    | '/lists/$listId/enrichments'
    | '/lists/$listId/statistics'
    | '/profile/$profileId/admin-confirm'
    | '/profile/$profileId/confirm'
    | '/admin/users'
    | '/libraries/$libraryId/'
    | '/lists/$listId/'
    | '/libraries/$libraryId/crawlers/$crawlerId'
    | '/libraries/$libraryId/files/$fileId'
    | '/conversations/$conversationId/confirm-invitation/$invitationId'
    | '/libraries/$libraryId/crawlers/'
    | '/libraries/$libraryId/files'
    | '/libraries/$libraryId/crawlers/$crawlerId/runs'
    | '/libraries/$libraryId/files/$fileId/chunks'
    | '/libraries/$libraryId/files/$fileId/similarity'
    | '/libraries/$libraryId/files/$fileId/tasks'
    | '/libraries/$libraryId/crawlers/$crawlerId/'
    | '/libraries/$libraryId/files/$fileId/'
    | '/libraries/$libraryId/crawlers/$crawlerId/runs/$crawlerRunId'
    | '/libraries/$libraryId/crawlers/$crawlerId/runs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/ai-services'
    | '/admin/queues'
    | '/assistants/$assistantId'
    | '/conversations/$conversationId'
    | '/libraries/auth-google'
    | '/admin'
    | '/assistants'
    | '/conversations'
    | '/libraries'
    | '/lists'
    | '/profile'
    | '/admin/users/$userId'
    | '/libraries/$libraryId/postprocess'
    | '/libraries/$libraryId/processing'
    | '/libraries/$libraryId/query'
    | '/libraries/$libraryId/settings'
    | '/libraries/$libraryId/updates'
    | '/lists/$listId/edit'
    | '/lists/$listId/enrichments'
    | '/lists/$listId/statistics'
    | '/profile/$profileId/admin-confirm'
    | '/profile/$profileId/confirm'
    | '/admin/users'
    | '/libraries/$libraryId'
    | '/lists/$listId'
    | '/conversations/$conversationId/confirm-invitation/$invitationId'
    | '/libraries/$libraryId/crawlers'
    | '/libraries/$libraryId/files'
    | '/libraries/$libraryId/files/$fileId/chunks'
    | '/libraries/$libraryId/files/$fileId/similarity'
    | '/libraries/$libraryId/files/$fileId/tasks'
    | '/libraries/$libraryId/crawlers/$crawlerId'
    | '/libraries/$libraryId/files/$fileId'
    | '/libraries/$libraryId/crawlers/$crawlerId/runs/$crawlerRunId'
    | '/libraries/$libraryId/crawlers/$crawlerId/runs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/conversations'
    | '/_authenticated/libraries/$libraryId'
    | '/_authenticated/lists/$listId'
    | '/_authenticated/admin/ai-services'
    | '/_authenticated/admin/queues'
    | '/_authenticated/assistants/$assistantId'
    | '/_authenticated/conversations/$conversationId'
    | '/_authenticated/libraries/auth-google'
    | '/_authenticated/admin/'
    | '/_authenticated/assistants/'
    | '/_authenticated/conversations/'
    | '/_authenticated/libraries/'
    | '/_authenticated/lists/'
    | '/_authenticated/profile/'
    | '/_authenticated/libraries/$libraryId/crawlers'
    | '/_authenticated/admin/users/$userId'
    | '/_authenticated/libraries/$libraryId/postprocess'
    | '/_authenticated/libraries/$libraryId/processing'
    | '/_authenticated/libraries/$libraryId/query'
    | '/_authenticated/libraries/$libraryId/settings'
    | '/_authenticated/libraries/$libraryId/updates'
    | '/_authenticated/lists/$listId/edit'
    | '/_authenticated/lists/$listId/enrichments'
    | '/_authenticated/lists/$listId/statistics'
    | '/_authenticated/profile/$profileId/admin-confirm'
    | '/_authenticated/profile/$profileId/confirm'
    | '/_authenticated/admin/users/'
    | '/_authenticated/libraries/$libraryId/'
    | '/_authenticated/lists/$listId/'
    | '/_authenticated/libraries/$libraryId/crawlers/$crawlerId'
    | '/_authenticated/libraries/$libraryId/files/$fileId'
    | '/_authenticated/conversations/$conversationId_/confirm-invitation/$invitationId'
    | '/_authenticated/libraries/$libraryId/crawlers/'
    | '/_authenticated/libraries/$libraryId/files/'
    | '/_authenticated/libraries/$libraryId/crawlers/$crawlerId/runs'
    | '/_authenticated/libraries/$libraryId/files/$fileId/chunks'
    | '/_authenticated/libraries/$libraryId/files/$fileId/similarity'
    | '/_authenticated/libraries/$libraryId/files/$fileId/tasks'
    | '/_authenticated/libraries/$libraryId/crawlers/$crawlerId/'
    | '/_authenticated/libraries/$libraryId/files/$fileId/'
    | '/_authenticated/libraries/$libraryId/crawlers/$crawlerId/runs/$crawlerRunId'
    | '/_authenticated/libraries/$libraryId/crawlers/$crawlerId/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/conversations': {
      id: '/_authenticated/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AuthenticatedConversationsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lists/': {
      id: '/_authenticated/lists/'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof AuthenticatedListsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/libraries/': {
      id: '/_authenticated/libraries/'
      path: '/libraries'
      fullPath: '/libraries'
      preLoaderRoute: typeof AuthenticatedLibrariesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversations/': {
      id: '/_authenticated/conversations/'
      path: '/'
      fullPath: '/conversations/'
      preLoaderRoute: typeof AuthenticatedConversationsIndexRouteImport
      parentRoute: typeof AuthenticatedConversationsRouteRoute
    }
    '/_authenticated/assistants/': {
      id: '/_authenticated/assistants/'
      path: '/assistants'
      fullPath: '/assistants'
      preLoaderRoute: typeof AuthenticatedAssistantsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/libraries/auth-google': {
      id: '/_authenticated/libraries/auth-google'
      path: '/libraries/auth-google'
      fullPath: '/libraries/auth-google'
      preLoaderRoute: typeof AuthenticatedLibrariesAuthGoogleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversations/$conversationId': {
      id: '/_authenticated/conversations/$conversationId'
      path: '/$conversationId'
      fullPath: '/conversations/$conversationId'
      preLoaderRoute: typeof AuthenticatedConversationsConversationIdRouteImport
      parentRoute: typeof AuthenticatedConversationsRouteRoute
    }
    '/_authenticated/assistants/$assistantId': {
      id: '/_authenticated/assistants/$assistantId'
      path: '/assistants/$assistantId'
      fullPath: '/assistants/$assistantId'
      preLoaderRoute: typeof AuthenticatedAssistantsAssistantIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/queues': {
      id: '/_authenticated/admin/queues'
      path: '/queues'
      fullPath: '/admin/queues'
      preLoaderRoute: typeof AuthenticatedAdminQueuesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ai-services': {
      id: '/_authenticated/admin/ai-services'
      path: '/ai-services'
      fullPath: '/admin/ai-services'
      preLoaderRoute: typeof AuthenticatedAdminAiServicesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/lists/$listId': {
      id: '/_authenticated/lists/$listId'
      path: '/lists/$listId'
      fullPath: '/lists/$listId'
      preLoaderRoute: typeof AuthenticatedListsListIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/libraries/$libraryId': {
      id: '/_authenticated/libraries/$libraryId'
      path: '/libraries/$libraryId'
      fullPath: '/libraries/$libraryId'
      preLoaderRoute: typeof AuthenticatedLibrariesLibraryIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lists/$listId/': {
      id: '/_authenticated/lists/$listId/'
      path: '/'
      fullPath: '/lists/$listId/'
      preLoaderRoute: typeof AuthenticatedListsListIdIndexRouteImport
      parentRoute: typeof AuthenticatedListsListIdRouteRoute
    }
    '/_authenticated/libraries/$libraryId/': {
      id: '/_authenticated/libraries/$libraryId/'
      path: '/'
      fullPath: '/libraries/$libraryId/'
      preLoaderRoute: typeof AuthenticatedLibrariesLibraryIdIndexRouteImport
      parentRoute: typeof AuthenticatedLibrariesLibraryIdRouteRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/profile/$profileId/confirm': {
      id: '/_authenticated/profile/$profileId/confirm'
      path: '/profile/$profileId/confirm'
      fullPath: '/profile/$profileId/confirm'
      preLoaderRoute: typeof AuthenticatedProfileProfileIdConfirmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/$profileId/admin-confirm': {
      id: '/_authenticated/profile/$profileId/admin-confirm'
      path: '/profile/$profileId/admin-confirm'
      fullPath: '/profile/$profileId/admin-confirm'
      preLoaderRoute: typeof AuthenticatedProfileProfileIdAdminConfirmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lists/$listId/statistics': {
      id: '/_authenticated/lists/$listId/statistics'
      path: '/statistics'
      fullPath: '/lists/$listId/statistics'
      preLoaderRoute: typeof AuthenticatedListsListIdStatisticsRouteImport
      parentRoute: typeof AuthenticatedListsListIdRouteRoute
    }
    '/_authenticated/lists/$listId/enrichments': {
      id: '/_authenticated/lists/$listId/enrichments'
      path: '/enrichments'
      fullPath: '/lists/$listId/enrichments'
      preLoaderRoute: typeof AuthenticatedListsListIdEnrichmentsRouteImport
      parentRoute: typeof AuthenticatedListsListIdRouteRoute
    }
    '/_authenticated/lists/$listId/edit': {
      id: '/_authenticated/lists/$listId/edit'
      path: '/edit'
      fullPath: '/lists/$listId/edit'
      preLoaderRoute: typeof AuthenticatedListsListIdEditRouteImport
      parentRoute: typeof AuthenticatedListsListIdRouteRoute
    }
    '/_authenticated/libraries/$libraryId/updates': {
      id: '/_authenticated/libraries/$libraryId/updates'
      path: '/updates'
      fullPath: '/libraries/$libraryId/updates'
      preLoaderRoute: typeof AuthenticatedLibrariesLibraryIdUpdatesRouteImport
      parentRoute: typeof AuthenticatedLibrariesLibraryIdRouteRoute
    }
    '/_authenticated/libraries/$libraryId/settings': {
      id: '/_authenticated/libraries/$libraryId/settings'
      path: '/settings'
      fullPath: '/libraries/$libraryId/settings'
      preLoaderRoute: typeof AuthenticatedLibrariesLibraryIdSettingsRouteImport
      parentRoute: typeof AuthenticatedLibrariesLibraryIdRouteRoute
    }
    '/_authenticated/libraries/$libraryId/query': {
      id: '/_authenticated/libraries/$libraryId/query'
      path: '/query'
      fullPath: '/libraries/$libraryId/query'
      preLoaderRoute: typeof AuthenticatedLibrariesLibraryIdQueryRouteImport
      parentRoute: typeof AuthenticatedLibrariesLibraryIdRouteRoute
    }
    '/_authenticated/libraries/$libraryId/processing': {
      id: '/_authenticated/libraries/$libraryId/processing'
      path: '/processing'
      fullPath: '/libraries/$libraryId/processing'
      preLoaderRoute: typeof AuthenticatedLibrariesLibraryIdProcessingRouteImport
      parentRoute: typeof AuthenticatedLibrariesLibraryIdRouteRoute
    }
    '/_authenticated/libraries/$libraryId/postprocess': {
      id: '/_authenticated/libraries/$libraryId/postprocess'
      path: '/postprocess'
      fullPath: '/libraries/$libraryId/postprocess'
      preLoaderRoute: typeof AuthenticatedLibrariesLibraryIdPostprocessRouteImport
      parentRoute: typeof AuthenticatedLibrariesLibraryIdRouteRoute
    }
    '/_authenticated/admin/users/$userId': {
      id: '/_authenticated/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/libraries/$libraryId/crawlers': {
      id: '/_authenticated/libraries/$libraryId/crawlers'
      path: '/crawlers'
      fullPath: '/libraries/$libraryId/crawlers'
      preLoaderRoute: typeof AuthenticatedLibrariesLibraryIdCrawlersRouteRouteImport
      parentRoute: typeof AuthenticatedLibrariesLibraryIdRouteRoute
    }
    '/_authenticated/libraries/$libraryId/files/': {
      id: '/_authenticated/libraries/$libraryId/files/'
      path: '/files'
      fullPath: '/libraries/$libraryId/files'
      preLoaderRoute: typeof AuthenticatedLibrariesLibraryIdFilesIndexRouteImport
      parentRoute: typeof AuthenticatedLibrariesLibraryIdRouteRoute
    }
    '/_authenticated/libraries/$libraryId/crawlers/': {
      id: '/_authenticated/libraries/$libraryId/crawlers/'
      path: '/'
      fullPath: '/libraries/$libraryId/crawlers/'
      preLoaderRoute: typeof AuthenticatedLibrariesLibraryIdCrawlersIndexRouteImport
      parentRoute: typeof AuthenticatedLibrariesLibraryIdCrawlersRouteRoute
    }
    '/_authenticated/conversations/$conversationId_/confirm-invitation/$invitationId': {
      id: '/_authenticated/conversations/$conversationId_/confirm-invitation/$invitationId'
      path: '/$conversationId/confirm-invitation/$invitationId'
      fullPath: '/conversations/$conversationId/confirm-invitation/$invitationId'
      preLoaderRoute: typeof AuthenticatedConversationsConversationIdConfirmInvitationInvitationIdRouteImport
      parentRoute: typeof AuthenticatedConversationsRouteRoute
    }
    '/_authenticated/libraries/$libraryId/files/$fileId': {
      id: '/_authenticated/libraries/$libraryId/files/$fileId'
      path: '/files/$fileId'
      fullPath: '/libraries/$libraryId/files/$fileId'
      preLoaderRoute: typeof AuthenticatedLibrariesLibraryIdFilesFileIdRouteRouteImport
      parentRoute: typeof AuthenticatedLibrariesLibraryIdRouteRoute
    }
    '/_authenticated/libraries/$libraryId/crawlers/$crawlerId': {
      id: '/_authenticated/libraries/$libraryId/crawlers/$crawlerId'
      path: '/$crawlerId'
      fullPath: '/libraries/$libraryId/crawlers/$crawlerId'
      preLoaderRoute: typeof AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRouteRouteImport
      parentRoute: typeof AuthenticatedLibrariesLibraryIdCrawlersRouteRoute
    }
    '/_authenticated/libraries/$libraryId/files/$fileId/': {
      id: '/_authenticated/libraries/$libraryId/files/$fileId/'
      path: '/'
      fullPath: '/libraries/$libraryId/files/$fileId/'
      preLoaderRoute: typeof AuthenticatedLibrariesLibraryIdFilesFileIdIndexRouteImport
      parentRoute: typeof AuthenticatedLibrariesLibraryIdFilesFileIdRouteRoute
    }
    '/_authenticated/libraries/$libraryId/crawlers/$crawlerId/': {
      id: '/_authenticated/libraries/$libraryId/crawlers/$crawlerId/'
      path: '/'
      fullPath: '/libraries/$libraryId/crawlers/$crawlerId/'
      preLoaderRoute: typeof AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdIndexRouteImport
      parentRoute: typeof AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRouteRoute
    }
    '/_authenticated/libraries/$libraryId/files/$fileId/tasks': {
      id: '/_authenticated/libraries/$libraryId/files/$fileId/tasks'
      path: '/tasks'
      fullPath: '/libraries/$libraryId/files/$fileId/tasks'
      preLoaderRoute: typeof AuthenticatedLibrariesLibraryIdFilesFileIdTasksRouteImport
      parentRoute: typeof AuthenticatedLibrariesLibraryIdFilesFileIdRouteRoute
    }
    '/_authenticated/libraries/$libraryId/files/$fileId/similarity': {
      id: '/_authenticated/libraries/$libraryId/files/$fileId/similarity'
      path: '/similarity'
      fullPath: '/libraries/$libraryId/files/$fileId/similarity'
      preLoaderRoute: typeof AuthenticatedLibrariesLibraryIdFilesFileIdSimilarityRouteImport
      parentRoute: typeof AuthenticatedLibrariesLibraryIdFilesFileIdRouteRoute
    }
    '/_authenticated/libraries/$libraryId/files/$fileId/chunks': {
      id: '/_authenticated/libraries/$libraryId/files/$fileId/chunks'
      path: '/chunks'
      fullPath: '/libraries/$libraryId/files/$fileId/chunks'
      preLoaderRoute: typeof AuthenticatedLibrariesLibraryIdFilesFileIdChunksRouteImport
      parentRoute: typeof AuthenticatedLibrariesLibraryIdFilesFileIdRouteRoute
    }
    '/_authenticated/libraries/$libraryId/crawlers/$crawlerId/runs': {
      id: '/_authenticated/libraries/$libraryId/crawlers/$crawlerId/runs'
      path: '/runs'
      fullPath: '/libraries/$libraryId/crawlers/$crawlerId/runs'
      preLoaderRoute: typeof AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsRouteRouteImport
      parentRoute: typeof AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRouteRoute
    }
    '/_authenticated/libraries/$libraryId/crawlers/$crawlerId/runs/': {
      id: '/_authenticated/libraries/$libraryId/crawlers/$crawlerId/runs/'
      path: '/'
      fullPath: '/libraries/$libraryId/crawlers/$crawlerId/runs/'
      preLoaderRoute: typeof AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsIndexRouteImport
      parentRoute: typeof AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsRouteRoute
    }
    '/_authenticated/libraries/$libraryId/crawlers/$crawlerId/runs/$crawlerRunId': {
      id: '/_authenticated/libraries/$libraryId/crawlers/$crawlerId/runs/$crawlerRunId'
      path: '/$crawlerRunId'
      fullPath: '/libraries/$libraryId/crawlers/$crawlerId/runs/$crawlerRunId'
      preLoaderRoute: typeof AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsCrawlerRunIdRouteImport
      parentRoute: typeof AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAiServicesRoute: typeof AuthenticatedAdminAiServicesRoute
  AuthenticatedAdminQueuesRoute: typeof AuthenticatedAdminQueuesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminUsersUserIdRoute: typeof AuthenticatedAdminUsersUserIdRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAiServicesRoute: AuthenticatedAdminAiServicesRoute,
    AuthenticatedAdminQueuesRoute: AuthenticatedAdminQueuesRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminUsersUserIdRoute: AuthenticatedAdminUsersUserIdRoute,
    AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedConversationsRouteRouteChildren {
  AuthenticatedConversationsConversationIdRoute: typeof AuthenticatedConversationsConversationIdRoute
  AuthenticatedConversationsIndexRoute: typeof AuthenticatedConversationsIndexRoute
  AuthenticatedConversationsConversationIdConfirmInvitationInvitationIdRoute: typeof AuthenticatedConversationsConversationIdConfirmInvitationInvitationIdRoute
}

const AuthenticatedConversationsRouteRouteChildren: AuthenticatedConversationsRouteRouteChildren =
  {
    AuthenticatedConversationsConversationIdRoute:
      AuthenticatedConversationsConversationIdRoute,
    AuthenticatedConversationsIndexRoute: AuthenticatedConversationsIndexRoute,
    AuthenticatedConversationsConversationIdConfirmInvitationInvitationIdRoute:
      AuthenticatedConversationsConversationIdConfirmInvitationInvitationIdRoute,
  }

const AuthenticatedConversationsRouteRouteWithChildren =
  AuthenticatedConversationsRouteRoute._addFileChildren(
    AuthenticatedConversationsRouteRouteChildren,
  )

interface AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsRouteRouteChildren {
  AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsCrawlerRunIdRoute: typeof AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsCrawlerRunIdRoute
  AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsIndexRoute: typeof AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsIndexRoute
}

const AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsRouteRouteChildren: AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsRouteRouteChildren =
  {
    AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsCrawlerRunIdRoute:
      AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsCrawlerRunIdRoute,
    AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsIndexRoute:
      AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsIndexRoute,
  }

const AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsRouteRouteWithChildren =
  AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsRouteRoute._addFileChildren(
    AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsRouteRouteChildren,
  )

interface AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRouteRouteChildren {
  AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsRouteRoute: typeof AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsRouteRouteWithChildren
  AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdIndexRoute: typeof AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdIndexRoute
}

const AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRouteRouteChildren: AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRouteRouteChildren =
  {
    AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsRouteRoute:
      AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRunsRouteRouteWithChildren,
    AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdIndexRoute:
      AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdIndexRoute,
  }

const AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRouteRouteWithChildren =
  AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRouteRoute._addFileChildren(
    AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRouteRouteChildren,
  )

interface AuthenticatedLibrariesLibraryIdCrawlersRouteRouteChildren {
  AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRouteRoute: typeof AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRouteRouteWithChildren
  AuthenticatedLibrariesLibraryIdCrawlersIndexRoute: typeof AuthenticatedLibrariesLibraryIdCrawlersIndexRoute
}

const AuthenticatedLibrariesLibraryIdCrawlersRouteRouteChildren: AuthenticatedLibrariesLibraryIdCrawlersRouteRouteChildren =
  {
    AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRouteRoute:
      AuthenticatedLibrariesLibraryIdCrawlersCrawlerIdRouteRouteWithChildren,
    AuthenticatedLibrariesLibraryIdCrawlersIndexRoute:
      AuthenticatedLibrariesLibraryIdCrawlersIndexRoute,
  }

const AuthenticatedLibrariesLibraryIdCrawlersRouteRouteWithChildren =
  AuthenticatedLibrariesLibraryIdCrawlersRouteRoute._addFileChildren(
    AuthenticatedLibrariesLibraryIdCrawlersRouteRouteChildren,
  )

interface AuthenticatedLibrariesLibraryIdFilesFileIdRouteRouteChildren {
  AuthenticatedLibrariesLibraryIdFilesFileIdChunksRoute: typeof AuthenticatedLibrariesLibraryIdFilesFileIdChunksRoute
  AuthenticatedLibrariesLibraryIdFilesFileIdSimilarityRoute: typeof AuthenticatedLibrariesLibraryIdFilesFileIdSimilarityRoute
  AuthenticatedLibrariesLibraryIdFilesFileIdTasksRoute: typeof AuthenticatedLibrariesLibraryIdFilesFileIdTasksRoute
  AuthenticatedLibrariesLibraryIdFilesFileIdIndexRoute: typeof AuthenticatedLibrariesLibraryIdFilesFileIdIndexRoute
}

const AuthenticatedLibrariesLibraryIdFilesFileIdRouteRouteChildren: AuthenticatedLibrariesLibraryIdFilesFileIdRouteRouteChildren =
  {
    AuthenticatedLibrariesLibraryIdFilesFileIdChunksRoute:
      AuthenticatedLibrariesLibraryIdFilesFileIdChunksRoute,
    AuthenticatedLibrariesLibraryIdFilesFileIdSimilarityRoute:
      AuthenticatedLibrariesLibraryIdFilesFileIdSimilarityRoute,
    AuthenticatedLibrariesLibraryIdFilesFileIdTasksRoute:
      AuthenticatedLibrariesLibraryIdFilesFileIdTasksRoute,
    AuthenticatedLibrariesLibraryIdFilesFileIdIndexRoute:
      AuthenticatedLibrariesLibraryIdFilesFileIdIndexRoute,
  }

const AuthenticatedLibrariesLibraryIdFilesFileIdRouteRouteWithChildren =
  AuthenticatedLibrariesLibraryIdFilesFileIdRouteRoute._addFileChildren(
    AuthenticatedLibrariesLibraryIdFilesFileIdRouteRouteChildren,
  )

interface AuthenticatedLibrariesLibraryIdRouteRouteChildren {
  AuthenticatedLibrariesLibraryIdCrawlersRouteRoute: typeof AuthenticatedLibrariesLibraryIdCrawlersRouteRouteWithChildren
  AuthenticatedLibrariesLibraryIdPostprocessRoute: typeof AuthenticatedLibrariesLibraryIdPostprocessRoute
  AuthenticatedLibrariesLibraryIdProcessingRoute: typeof AuthenticatedLibrariesLibraryIdProcessingRoute
  AuthenticatedLibrariesLibraryIdQueryRoute: typeof AuthenticatedLibrariesLibraryIdQueryRoute
  AuthenticatedLibrariesLibraryIdSettingsRoute: typeof AuthenticatedLibrariesLibraryIdSettingsRoute
  AuthenticatedLibrariesLibraryIdUpdatesRoute: typeof AuthenticatedLibrariesLibraryIdUpdatesRoute
  AuthenticatedLibrariesLibraryIdIndexRoute: typeof AuthenticatedLibrariesLibraryIdIndexRoute
  AuthenticatedLibrariesLibraryIdFilesFileIdRouteRoute: typeof AuthenticatedLibrariesLibraryIdFilesFileIdRouteRouteWithChildren
  AuthenticatedLibrariesLibraryIdFilesIndexRoute: typeof AuthenticatedLibrariesLibraryIdFilesIndexRoute
}

const AuthenticatedLibrariesLibraryIdRouteRouteChildren: AuthenticatedLibrariesLibraryIdRouteRouteChildren =
  {
    AuthenticatedLibrariesLibraryIdCrawlersRouteRoute:
      AuthenticatedLibrariesLibraryIdCrawlersRouteRouteWithChildren,
    AuthenticatedLibrariesLibraryIdPostprocessRoute:
      AuthenticatedLibrariesLibraryIdPostprocessRoute,
    AuthenticatedLibrariesLibraryIdProcessingRoute:
      AuthenticatedLibrariesLibraryIdProcessingRoute,
    AuthenticatedLibrariesLibraryIdQueryRoute:
      AuthenticatedLibrariesLibraryIdQueryRoute,
    AuthenticatedLibrariesLibraryIdSettingsRoute:
      AuthenticatedLibrariesLibraryIdSettingsRoute,
    AuthenticatedLibrariesLibraryIdUpdatesRoute:
      AuthenticatedLibrariesLibraryIdUpdatesRoute,
    AuthenticatedLibrariesLibraryIdIndexRoute:
      AuthenticatedLibrariesLibraryIdIndexRoute,
    AuthenticatedLibrariesLibraryIdFilesFileIdRouteRoute:
      AuthenticatedLibrariesLibraryIdFilesFileIdRouteRouteWithChildren,
    AuthenticatedLibrariesLibraryIdFilesIndexRoute:
      AuthenticatedLibrariesLibraryIdFilesIndexRoute,
  }

const AuthenticatedLibrariesLibraryIdRouteRouteWithChildren =
  AuthenticatedLibrariesLibraryIdRouteRoute._addFileChildren(
    AuthenticatedLibrariesLibraryIdRouteRouteChildren,
  )

interface AuthenticatedListsListIdRouteRouteChildren {
  AuthenticatedListsListIdEditRoute: typeof AuthenticatedListsListIdEditRoute
  AuthenticatedListsListIdEnrichmentsRoute: typeof AuthenticatedListsListIdEnrichmentsRoute
  AuthenticatedListsListIdStatisticsRoute: typeof AuthenticatedListsListIdStatisticsRoute
  AuthenticatedListsListIdIndexRoute: typeof AuthenticatedListsListIdIndexRoute
}

const AuthenticatedListsListIdRouteRouteChildren: AuthenticatedListsListIdRouteRouteChildren =
  {
    AuthenticatedListsListIdEditRoute: AuthenticatedListsListIdEditRoute,
    AuthenticatedListsListIdEnrichmentsRoute:
      AuthenticatedListsListIdEnrichmentsRoute,
    AuthenticatedListsListIdStatisticsRoute:
      AuthenticatedListsListIdStatisticsRoute,
    AuthenticatedListsListIdIndexRoute: AuthenticatedListsListIdIndexRoute,
  }

const AuthenticatedListsListIdRouteRouteWithChildren =
  AuthenticatedListsListIdRouteRoute._addFileChildren(
    AuthenticatedListsListIdRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedConversationsRouteRoute: typeof AuthenticatedConversationsRouteRouteWithChildren
  AuthenticatedLibrariesLibraryIdRouteRoute: typeof AuthenticatedLibrariesLibraryIdRouteRouteWithChildren
  AuthenticatedListsListIdRouteRoute: typeof AuthenticatedListsListIdRouteRouteWithChildren
  AuthenticatedAssistantsAssistantIdRoute: typeof AuthenticatedAssistantsAssistantIdRoute
  AuthenticatedLibrariesAuthGoogleRoute: typeof AuthenticatedLibrariesAuthGoogleRoute
  AuthenticatedAssistantsIndexRoute: typeof AuthenticatedAssistantsIndexRoute
  AuthenticatedLibrariesIndexRoute: typeof AuthenticatedLibrariesIndexRoute
  AuthenticatedListsIndexRoute: typeof AuthenticatedListsIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedProfileProfileIdAdminConfirmRoute: typeof AuthenticatedProfileProfileIdAdminConfirmRoute
  AuthenticatedProfileProfileIdConfirmRoute: typeof AuthenticatedProfileProfileIdConfirmRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedConversationsRouteRoute:
    AuthenticatedConversationsRouteRouteWithChildren,
  AuthenticatedLibrariesLibraryIdRouteRoute:
    AuthenticatedLibrariesLibraryIdRouteRouteWithChildren,
  AuthenticatedListsListIdRouteRoute:
    AuthenticatedListsListIdRouteRouteWithChildren,
  AuthenticatedAssistantsAssistantIdRoute:
    AuthenticatedAssistantsAssistantIdRoute,
  AuthenticatedLibrariesAuthGoogleRoute: AuthenticatedLibrariesAuthGoogleRoute,
  AuthenticatedAssistantsIndexRoute: AuthenticatedAssistantsIndexRoute,
  AuthenticatedLibrariesIndexRoute: AuthenticatedLibrariesIndexRoute,
  AuthenticatedListsIndexRoute: AuthenticatedListsIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedProfileProfileIdAdminConfirmRoute:
    AuthenticatedProfileProfileIdAdminConfirmRoute,
  AuthenticatedProfileProfileIdConfirmRoute:
    AuthenticatedProfileProfileIdConfirmRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
