version: '3.7'

services:
  gai-chatweb:
    image: ghcr.io/progwise/george-ai/chat-web:latest
    ports:
      - '3000:3000'
    network:
      - gai-network

  gai-typesense:
    image: typesense/typesense:27.1
    environment:
      - TYPESENSE_API_HOST=gai-typesense
      - TYPESENSE_API_PORT=8108
      - TYPESENSE_API_PROTOCOL=http
      - TYPESENSE_API_KEY=xyz
    ports:
      - '8108:8108'
    volumes:
      - ../.typesense-data:/typesensedata
    command: '--data-dir /typesensedata --enable-cors --enable-access-logging --enable-search-logging --log-dir=/typesensedata'
    network:
      - gai-network

  gai-pocketbase:
    image: ghcr.io/progwise/george-ai/pocketbase:latest
    environment:
      - GAI_WEBHOOK_URL=http://gai-chatweb:3000/api/process-documents
    ports:
      - '8090:8090'
    volumes:
      - ../apps/pocketbase/pb_data:/pb/pb_data
      - ../apps/pocketbase/pb_public:/pb/pb_public
      - ../apps/pocketbase/pb_hooks:/pb/pb_hooks
      - ../apps/pocketbase/pb_migrations:/pb/pb_migrations
    healthcheck: # optional, recommended since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://gai-pocketbase:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    network:
      - gai-network

networks:
  gai-network:
    driver: overlay
