name: Create and publish Docker images to ghcr.io/progwise/george-ai

on:
  workflow_dispatch:
    environment:
      description: 'Environment to run tests against'
      type: environment
      required: true
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  REGISTRY_PATH: ghcr.io/progwise/george-ai

jobs:
  build-and-push-docker:
    runs-on: ubuntu-22.04
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/metadata-action#about
      - name: Extract metadata (tags, labels) for chat-web
        id: meta-chat-web
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY_PATH }}/chat-web

      # https://github.com/docker/build-push-action#usage
      - name: Build and push chat-web
        id: push-chat-web
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          file: ./apps/chat-web/Dockerfile
          context: .
          push: true
          secrets: |
            TAVILY_API_KEY=${{ secrets.TAVILY_API_KEY }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          tags: ${{ steps.meta-chat-web.outputs.tags }}
          labels: ${{ steps.meta-chat-web.outputs.labels }}

      # This step generates an artifact attestation for the image, which is an unforgeable statement about where and how it was built.
      # It increases supply chain security for people who consume the image. For more information, see "[AUTOTITLE](/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds)."
      - name: Generate artifact attestation for chat-web
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY_PATH }}/chat-web
          subject-digest: ${{ steps.push-chat-web.outputs.digest }}
          push-to-registry: true
